version: '3.7'
services:
  app-server: # App backend service
    image: 781995/multiwebsites
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "8089:8089" # Forward the exposed port 8089 on the container to port 8089 on the host machine
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/multiwebsites
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mss123
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - backend
    depends_on: # This service depends on postgres. Start that first.
    - postgresql

  # Database Service (Postgres)
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment: # Pass environment variables to the service
      - POSTGRES_PASSWORD=mss123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=multiwebsites
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - backend
# volume to storage containers that can never be lost after restart of our machine
volumes:
       pg-data:
# Networks to be created to facilitate communication between containers
networks:
  backend: